#!/bin/bash

if [[ "$1" == "--tr" ]]; then
update-alternatives --get-selections | grep x-terminal-emulator | awk -F"[/]" '{print $4}' | awk -F"[.]" '{print $1}' | sh

elif [[ "$1" == "--ff" ]]; then
xdg-settings get default-web-browser | awk -F"[.]" '{print $1}' | sh


elif [[ "$1" == "--fm" ]]; then
xdg-mime query default inode/directory | awk -F"[.]" '{print tolower ($3)}' | sh

elif [[ "$1" == "--ge" ]]; then
	geany &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	firefox --new-tab "https://mail.google.com"

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu

fi
